{"name": "test_integer_add[整数加法_结果2]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 5 == 6", "trace": "self = <python_scripts.third_pytest_scripts_01.TestCase_Calculator.TestCal.TestCalculator object at 0x7fa49aac6b50>, a = 2, b = 4, expect = 5\n\n    @allure.story(\"整数加法\")\n    @pytest.mark.parametrize(\n        ['a', 'b', 'expect'],\n        [data for data in get_data('integer_add')],\n        ids=[\n            '整数加法_结果1',\n            '整数加法_结果2',\n            '整数加法_结果3',\n            '整数加法_结果4'\n        ])\n    def test_integer_add(self, a, b, expect):\n        result = self.cal.add(a, b)\n>       assert expect == result\nE       assert 5 == 6\n\nTestCal.py:63: AssertionError"}, "parameters": [{"name": "a", "value": "2"}, {"name": "b", "value": "4"}, {"name": "expect", "value": "5"}], "start": 1597461583041, "stop": 1597461583041, "uuid": "a8d87833-dd41-457c-b040-4e342b4580e8", "historyId": "6ad1aba5f0af1b618c3a6dee7afe2429", "testCaseId": "6827ed8a49cd5bcd3667adc9377a02af", "fullName": "TestCal.TestCalculator#test_integer_add", "labels": [{"name": "feature", "value": "计算器"}, {"name": "story", "value": "整数加法"}, {"name": "suite", "value": "TestCal"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "CreamK"}, {"name": "thread", "value": "65678-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCal"}]}