{"name": "test_integer_add[整数加法_结果4]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 101 == 100", "trace": "self = <python_scripts.third_pytest_scripts_01.TestCase_Calculator.TestCal.TestCalculator object at 0x7fd14220c210>, a = 89, b = 11, expect = 101\n\n    @pytest.mark.parametrize(\n        ['a', 'b', 'expect'],\n        [data for data in get_data('integer_add')],\n        ids=[\n            '整数加法_结果1',\n            '整数加法_结果2',\n            '整数加法_结果3',\n            '整数加法_结果4'\n        ])\n    def test_integer_add(self, a, b, expect):\n        result = self.cal.add(a, b)\n>       assert expect == result\nE       assert 101 == 100\n\nTestCal.py:59: AssertionError"}, "parameters": [{"name": "a", "value": "89"}, {"name": "b", "value": "11"}, {"name": "expect", "value": "101"}], "start": 1597458668568, "stop": 1597458668569, "uuid": "4dc384cf-69f3-4cbb-82ed-490ada7d8221", "historyId": "b9f2066a336b780623798e5c35a19331", "testCaseId": "6827ed8a49cd5bcd3667adc9377a02af", "fullName": "TestCal.TestCalculator#test_integer_add", "labels": [{"name": "suite", "value": "TestCal"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "CreamK"}, {"name": "thread", "value": "63325-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCal"}]}